# Generated by Django 4.1.3 on 2022-12-05 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the Label')),
                ('description', models.TextField(default='', verbose_name='Description of the Label')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('color', models.CharField(max_length=7, verbose_name='Color of the Label (in hex format)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the Wallet')),
                ('description', models.TextField(default='', verbose_name='Description of the Wallet')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('balance', models.IntegerField(default=0, verbose_name='Current Balance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Transaction Amount')),
                ('is_expense', models.BooleanField(default=True, verbose_name='Is it an expense?')),
                ('labels', models.ManyToManyField(to='api.label', verbose_name='Labels')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wallet', verbose_name='Wallet Used for Transaction')),
            ],
        ),
    ]
