# Generated by Django 4.1.3 on 2022-12-05 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date & Time of Transaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='day',
            field=models.IntegerField(default=1, verbose_name='Date of the Month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='month',
            field=models.IntegerField(default=1, verbose_name='Month Of the Year'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='week',
            field=models.IntegerField(default=1, verbose_name='Week of the Month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='year',
            field=models.IntegerField(default=2022, verbose_name='Year of Transaction'),
            preserve_default=False,
        ),
    ]
